// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('calculadora', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('calculadora', async function() {
    await driver.get("http://host.docker.internal:8181/calculadora")
    await driver.manage().window().setRect({ width: 1534, height: 814 })
    assert(await driver.getTitle() == "Calculadora")
    await driver.findElement(By.css(".btnDigito:nth-child(8)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(7)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(6)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(10)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(11)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(12)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(20)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(19)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(14)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(15)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(16)")).click()
    await driver.findElement(By.css(".btnDigito:nth-child(18)")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "-987456,0123")
    await driver.findElement(By.id("btnBorrar")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "-987456,012")
    await driver.findElement(By.id("btnIniciar")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "0")
    await driver.findElement(By.css(".btnDigito:nth-child(14)")).click()
    await driver.findElement(By.css(".btnOperar:nth-child(5)")).click()
    assert(await driver.findElement(By.id("txtResumen")).getText() == "1 +")
    await driver.findElement(By.css(".btnDigito:nth-child(15)")).click()
    {
      const element = await driver.findElement(By.css(".btnOperar:nth-child(9)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".btnOperar:nth-child(9)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".btnOperar:nth-child(9)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".btnOperar:nth-child(9)")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "3")
    assert(await driver.getTitle() == "Calculadora")
    await driver.findElement(By.css(".btnDigito:nth-child(14)")).click()
    await driver.findElement(By.css(".btnOperar:nth-child(13)")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "2")
    assert(await driver.findElement(By.id("txtResumen")).getText() == "2 *")
    await driver.findElement(By.css(".btnDigito:nth-child(16)")).click()
    await driver.findElement(By.css(".btnOperar:nth-child(17)")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "6")
    assert(await driver.findElement(By.id("txtResumen")).getText() == "6 /")
    await driver.findElement(By.css(".btnDigito:nth-child(19)")).click()
    await driver.findElement(By.css(".btnOperar:nth-child(21)")).click()
    assert(await driver.findElement(By.id("txtPantalla")).getText() == "Infinity")
  })
})
